---
# default settings
env:
    browser: true
    es6: true
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 2018
    sourceType: module

extends:
    - plugin:prettier/recommended
plugins:
    - prettier

rules:
    prettier/prettier:
        - error
        - arrowParens: always
          bracketSpacing: true
          printWidth: 100
          semi: false
          singleQuote: true
